// automatically generated by the FlatBuffers compiler, do not modify

import { ArgsArray } from '../redis-request/args-array.js';
import { ArgsVecPointer } from '../redis-request/args-vec-pointer.js';


export enum ArgsOptions {
  NONE = 0,
  ArgsArray = 1,
  ArgsVecPointer = 2
}

export function unionToArgsOptions(
  type: ArgsOptions,
  accessor: (obj:ArgsArray|ArgsVecPointer) => ArgsArray|ArgsVecPointer|null
): ArgsArray|ArgsVecPointer|null {
  switch(ArgsOptions[type]) {
    case 'NONE': return null; 
    case 'ArgsArray': return accessor(new ArgsArray())! as ArgsArray;
    case 'ArgsVecPointer': return accessor(new ArgsVecPointer())! as ArgsVecPointer;
    default: return null;
  }
}

export function unionListToArgsOptions(
  type: ArgsOptions, 
  accessor: (index: number, obj:ArgsArray|ArgsVecPointer) => ArgsArray|ArgsVecPointer|null, 
  index: number
): ArgsArray|ArgsVecPointer|null {
  switch(ArgsOptions[type]) {
    case 'NONE': return null; 
    case 'ArgsArray': return accessor(index, new ArgsArray())! as ArgsArray;
    case 'ArgsVecPointer': return accessor(index, new ArgsVecPointer())! as ArgsVecPointer;
    default: return null;
  }
}
