// automatically generated by the FlatBuffers compiler, do not modify

import { Command } from '../redis-request/command.js';
import { Transaction } from '../redis-request/transaction.js';


export enum CommandOptions {
  NONE = 0,
  Command = 1,
  Transaction = 2
}

export function unionToCommandOptions(
  type: CommandOptions,
  accessor: (obj:Command|Transaction) => Command|Transaction|null
): Command|Transaction|null {
  switch(CommandOptions[type]) {
    case 'NONE': return null; 
    case 'Command': return accessor(new Command())! as Command;
    case 'Transaction': return accessor(new Transaction())! as Transaction;
    default: return null;
  }
}

export function unionListToCommandOptions(
  type: CommandOptions, 
  accessor: (index: number, obj:Command|Transaction) => Command|Transaction|null, 
  index: number
): Command|Transaction|null {
  switch(CommandOptions[type]) {
    case 'NONE': return null; 
    case 'Command': return accessor(index, new Command())! as Command;
    case 'Transaction': return accessor(index, new Transaction())! as Transaction;
    default: return null;
  }
}
