// automatically generated by the FlatBuffers compiler, do not modify

export enum RequestType {
  /**
   * Invalid request type
   */
  InvalidRequest = 0,

  /**
   * An unknown command, where all arguments are defined by the user.
   */
  CustomCommand = 1,

  /**
   * Type of a get string request.
   */
  GetString = 2,

  /**
   * Type of a set string request.
   */
  SetString = 3,
  Ping = 4,
  Info = 5,
  Del = 6,
  Select = 7,
  ConfigGet = 8,
  ConfigSet = 9,
  ConfigResetStat = 10,
  ConfigRewrite = 11,
  ClientGetName = 12,
  ClientGetRedir = 13,
  ClientId = 14,
  ClientInfo = 15,
  ClientKill = 16,
  ClientList = 17,
  ClientNoEvict = 18,
  ClientNoTouch = 19,
  ClientPause = 20,
  ClientReply = 21,
  ClientSetInfo = 22,
  ClientSetName = 23,
  ClientUnblock = 24,
  ClientUnpause = 25,
  Expire = 26,
  HashSet = 27,
  HashGet = 28,
  HashDel = 29,
  HashExists = 30,
  MGet = 31,
  MSet = 32,
  Incr = 33,
  IncrBy = 34,
  Decr = 35,
  IncrByFloat = 36,
  DecrBy = 37,
  HashGetAll = 38,
  HashMSet = 39,
  HashMGet = 40,
  HashIncrBy = 41,
  HashIncrByFloat = 42,
  LPush = 43,
  LPop = 44,
  RPush = 45,
  RPop = 46,
  LLen = 47,
  LRem = 48,
  LRange = 49,
  LTrim = 50,
  SAdd = 51,
  SRem = 52,
  SMembers = 53,
  SCard = 54,
  PExpireAt = 55,
  PExpire = 56,
  ExpireAt = 57,
  Exists = 58,
  Unlink = 59,
  TTL = 60
}
