/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class AsyncClient2Strings {
  static CreateConnection(connectionAddress: string): Promise<AsyncClient2Strings>
  get(key: string): Promise<string | null>
  set(key: string, value: string): Promise<void>
}
export class AsyncClientReceiveString {
  static CreateConnection(connectionAddress: string): Promise<AsyncClientReceiveString>
  get(connectionAddress: string): Promise<undefined | null>
  set(key: string, value: string): Promise<void>
}
export class AsyncClientReturnString {
  static CreateConnection(str: string): Promise<AsyncClientReturnString>
  get(): Promise<string | null>
  set(): Promise<void>
}
export class AsyncClient0String {
  static CreateConnection(connectionAddress: string): Promise<AsyncClient0String>
  get(): Promise<string | null>
  set(): Promise<void>
}
export class AsyncClientReceiveRawPointer {
  static CreateConnection(connectionAddress: string): Promise<AsyncClientReceiveRawPointer>
  get(pointer: RawSendPointer): Promise<undefined | null>
  set(key: RawSendPointer, val: RawSendPointer): Promise<void>
}
