/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class AsyncClient2Strings {
  static CreateConnection(connectionAddress: string): Promise<AsyncClient2Strings>
  get(key: string): Promise<string | null>
  set(key: string, value: string): Promise<void>
}
export class AsyncClientReceiveString {
  static CreateConnection(connectionAddress: string): Promise<AsyncClientReceiveString>
  get(key: string): Promise<string | null>
  set(key: string, value: string): Promise<void>
}
export class AsyncClientReturnString {
  static CreateConnection(connectionAddress: string): Promise<AsyncClientReturnString>
  get(key: string): Promise<string | null>
  set(key: string, value: string): Promise<void>
}
export class AsyncClient0String {
  static CreateConnection(connectionAddress: string): Promise<AsyncClient0String>
  get(key: string): Promise<string | null>
  set(key: string, value: string): Promise<void>
}
