name: C# tests

on:
    push:
        branches: ["main"]
        paths:
            - csharp/**
            - babushka-core/**
            - submodules/**
            - ./**/*.cs
    pull_request:
        paths:
            - csharp/**
            - babushka-core/src/**
            - submodules/**
            - ./**/*.cs

permissions:
    contents: read

jobs:
    run-tests:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                redis:
                    - 7.2.0
                    # TODO - add older version to matrix once this is close to being production ready.

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install redis
              uses: ./.github/workflows/install-redis
              with:
                  redis-version: ${{ matrix.redis }}

            - name: Install protoc
              run: |
                  sudo apt update
                  sudo apt install protobuf-compiler

            - name: Set up dotnet
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 6.0.x

            - name: Start redis server
              run: redis-server &

            - name: Test
              working-directory: ./csharp
              run: dotnet test

    lint-rust:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./csharp/lib

    test-benchmark:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: ./.github/workflows/test-benchmark
              with:
                  language-flag: -csharp
