name: Rust tests

on:
    push:
        branches: [main]
        paths:
            - logger_core/**
            - babushka-core/**
            - submodules/**
            - utils/cluster_manager.py
            - ./**/*.rs
    pull_request:
        paths:
            - logger_core/**
            - babushka-core/**
            - submodules/**
            - utils/cluster_manager.py
            - ./**/*.rs

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            fail-fast: false
            matrix:
                redis:
                    - 6.2.13
                    - 7.2.0

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install redis
              uses: ./.github/workflows/install-redis
              with:
                  redis-version: ${{ matrix.redis }}

            - name: Install protoc
              run: |
                  sudo apt update
                  sudo apt install protobuf-compiler

            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2

            - name: Run tests
              working-directory: ./babushka-core
              run: cargo test -- --nocapture --test-threads=1 # TODO remove the concurrency limit after we fix test flakyness.

            - name: Run logger tests
              working-directory: ./logger_core
              run: cargo test -- --nocapture --test-threads=1

            - name: Check features
              working-directory: ./babushka-core
              run: |
                  cargo check --benches --all-features
                  cargo check --no-default-features

    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./babushka-core
              name: lint babushka-core

            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./logger_core
              name: lint logger

            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./benchmarks/rust
              name: lint benchmark

    test-benchmark:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: ./.github/workflows/test-benchmark
              with:
                  language-flag: -rust
